[package]
name = "searx-randomizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.6.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"


